apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  test-key: gAAAAABe5uJtbNKHp5xkMMBIJ9SrMZr6_IG3cnthp2fz4kNctGNgYQP_2ctu_LRH-Igxejfm16lmexTDCYOJF81c6Ttk_tI_qg==
  test-key1: gAAAAABe5jQchWyr0TFnDbbEIvrlxPR9cpwqyz6MhZOdF9uibgpWrF9O7kwUY608xzCFgnc1vAUFWROx9xSA0nIWcAgsQxFFXw==
  username: YWRtaW4=
kind: Secret
metadata:
  name: mysecret
type: Opaque
