apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  test-key: gAAAAABe5tzpOVsHPnSBxKxyCzS_yaxrTIaucAUOlY4dQOQm6_5xQSY190kIp7VnaPvSFqukSqnOLEafesXjHn9sHpRvyruWhQ==
  test-key1: gAAAAABe5jQchWyr0TFnDbbEIvrlxPR9cpwqyz6MhZOdF9uibgpWrF9O7kwUY608xzCFgnc1vAUFWROx9xSA0nIWcAgsQxFFXw==
  username: YWRtaW4=
kind: Secret
metadata:
  name: mysecret
type: Opaque
